-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 15:14:12 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HSC
-- -----------------------------------------------------
-- HOME-SCHOOL-COMMUNICATION
-- 

-- -----------------------------------------------------
-- Schema HSC
--
-- HOME-SCHOOL-COMMUNICATION
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HSC` DEFAULT CHARACTER SET utf8 ;
USE `HSC` ;

-- -----------------------------------------------------
-- Table `HSC`.`hsc_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classname` VARCHAR(45) NULL COMMENT '班级名称',
  `manager` VARCHAR(45) NULL COMMENT '班主任',
  `c_time` INT NULL,
  `u_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_class_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `stu_number` VARCHAR(45) NULL COMMENT '学号',
  `info` VARCHAR(200) NULL COMMENT '学生信息',
  `icon` VARCHAR(100) NULL COMMENT '学生头像',
  `type` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '评奖类型',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1可用，0禁用',
  `c_time` INT NULL COMMENT '统一c_time为创建时间',
  `u_time` INT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`id`, `hsc_class_id`),
  INDEX `fk_hsc_student_hsc_class1_idx` (`hsc_class_id` ASC),
  CONSTRAINT `fk_hsc_student_hsc_class1`
    FOREIGN KEY (`hsc_class_id`)
    REFERENCES `HSC`.`hsc_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `level` TINYINT(1) NOT NULL COMMENT '管理员等级1-9',
  `c_time` INT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1可用，0禁用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_share` (
  `hsc_manager_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `hsc_sharecol` VARCHAR(45) NULL,
  PRIMARY KEY (`hsc_manager_id`),
  CONSTRAINT `fk_hsc_share_hsc_manager1`
    FOREIGN KEY (`hsc_manager_id`)
    REFERENCES `HSC`.`hsc_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_manager_id` INT NOT NULL COMMENT ' 管理员id',
  `title` VARCHAR(45) NOT NULL COMMENT '标题',
  `content` TEXT(1000) NULL COMMENT '内容\n',
  `pic` VARCHAR(200) NULL COMMENT '缩略图',
  `like` INT NOT NULL DEFAULT 0 COMMENT '喜欢 点击增加',
  `type` VARCHAR(20) NOT NULL DEFAULT 'article' COMMENT 'share  分享\neveryday  每日一句\nnotice  通知\nvote  投票\nfeedback 反馈\narticle',
  `readtime` INT NOT NULL DEFAULT 0 COMMENT '阅读次数',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态1可用',
  `c_time` INT NULL,
  `u_time` INT NULL COMMENT '最后编辑时间',
  PRIMARY KEY (`id`, `hsc_manager_id`, `type`),
  CONSTRAINT `fk_hsc_everyday_hsc_manager1`
    FOREIGN KEY (`hsc_manager_id`)
    REFERENCES `HSC`.`hsc_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL COMMENT '课程名称',
  `info` VARCHAR(1000) NULL COMMENT '课程信息',
  `type` VARCHAR(45) NULL COMMENT '课程类型 公选 必修',
  `score` VARCHAR(45) NULL COMMENT '课程学分',
  `level` VARCHAR(45) NULL COMMENT '课程年级\n初一初二初三\n高一高二高三',
  `status` VARCHAR(45) NULL COMMENT '课程状态',
  `c_time` INT NULL COMMENT '课程时间',
  `u_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_manager_id` INT NOT NULL COMMENT '管理员id这里区分不同管理员',
  `title` VARCHAR(45) NULL COMMENT '通知标题',
  `content` TEXT(1000) NULL COMMENT '通知内容',
  `readtime` INT NULL COMMENT '阅读次数',
  `sort` TINYINT(1) NULL DEFAULT 1 COMMENT '排序等级1-9',
  `c_time` INT NULL COMMENT '发布日期',
  PRIMARY KEY (`id`, `hsc_manager_id`),
  INDEX `fk_hsc_notice_hsc_manager1_idx` (`hsc_manager_id` ASC),
  CONSTRAINT `fk_hsc_notice_hsc_manager1`
    FOREIGN KEY (`hsc_manager_id`)
    REFERENCES `HSC`.`hsc_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_student_id` INT NOT NULL,
  `hsc_class_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL COMMENT 'Math\nChines\nPhysic\nChemistry\nBiology',
  `score` VARCHAR(45) NULL COMMENT '分数',
  `exam_name` VARCHAR(45) NULL COMMENT '考试名称',
  `datetime` INT NOT NULL COMMENT '考试时间',
  PRIMARY KEY (`id`, `hsc_student_id`, `hsc_class_id`),
  INDEX `fk_hsc_score_hsc_student1_idx` (`hsc_student_id` ASC),
  INDEX `fk_hsc_score_hsc_class1_idx` (`hsc_class_id` ASC),
  CONSTRAINT `fk_hsc_score_hsc_student1`
    FOREIGN KEY (`hsc_student_id`)
    REFERENCES `HSC`.`hsc_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_score_hsc_class1`
    FOREIGN KEY (`hsc_class_id`)
    REFERENCES `HSC`.`hsc_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_parents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL COMMENT '姓名',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `sort` TINYINT(1) NULL COMMENT '1-9排序等级',
  `realname` VARCHAR(45) NULL COMMENT '真实姓名',
  `phone` VARCHAR(45) NULL COMMENT '可以设置多个',
  `email` VARCHAR(45) NULL,
  `stauts` TINYINT(1) NULL,
  `c_time` INT NULL COMMENT '创建时间',
  `u_time` INT NULL COMMENT '最后编辑时间\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_parents_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` TEXT(1000) NOT NULL,
  `c_time` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `hsc_ordercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `hsc_parents_id`),
  INDEX `fk_hsc_order_hsc_parents1_idx` (`hsc_parents_id` ASC),
  CONSTRAINT `fk_hsc_order_hsc_parents1`
    FOREIGN KEY (`hsc_parents_id`)
    REFERENCES `HSC`.`hsc_parents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_parents_num`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_parents_num` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_parents_id` INT NOT NULL,
  `parent_number` VARCHAR(45) NULL COMMENT '家长号 必须认证才能获得与家长一对一',
  `status` TINYINT(1) NULL,
  `c_time` INT NULL,
  `u_time` VARCHAR(45) NULL COMMENT '最后修改密码',
  PRIMARY KEY (`id`, `hsc_parents_id`),
  INDEX `fk_hsc_parents_num_hsc_parents1_idx` (`hsc_parents_id` ASC),
  CONSTRAINT `fk_hsc_parents_num_hsc_parents1`
    FOREIGN KEY (`hsc_parents_id`)
    REFERENCES `HSC`.`hsc_parents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `teacher_number` VARCHAR(45) NULL COMMENT '教师工号',
  `teach_type` VARCHAR(45) NULL COMMENT '教授科目math Chinese',
  `realname` VARCHAR(45) NOT NULL COMMENT '真实姓名',
  `email` VARCHAR(60) NULL COMMENT '邮箱',
  `is_order` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可预约,默认可预约',
  `icon` VARCHAR(200) NULL,
  `phone` VARCHAR(30) NULL,
  `info` TEXT(1000) NULL COMMENT '基本信息介绍',
  `status` VARCHAR(45) NULL COMMENT '在职状态',
  `c_time` INT NULL,
  `u_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_lesson_has_hsc_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_lesson_has_hsc_teacher` (
  `hsc_lesson_id` INT NOT NULL,
  `hsc_teacher_id` INT NOT NULL,
  PRIMARY KEY (`hsc_lesson_id`, `hsc_teacher_id`),
  INDEX `fk_hsc_lesson_has_hsc_teacher_hsc_teacher1_idx` (`hsc_teacher_id` ASC),
  INDEX `fk_hsc_lesson_has_hsc_teacher_hsc_lesson1_idx` (`hsc_lesson_id` ASC),
  CONSTRAINT `fk_hsc_lesson_has_hsc_teacher_hsc_lesson1`
    FOREIGN KEY (`hsc_lesson_id`)
    REFERENCES `HSC`.`hsc_lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_lesson_has_hsc_teacher_hsc_teacher1`
    FOREIGN KEY (`hsc_teacher_id`)
    REFERENCES `HSC`.`hsc_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_parents_has_hsc_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_parents_has_hsc_student` (
  `hsc_parents_id` INT NOT NULL,
  `hsc_student_id` INT NOT NULL,
  PRIMARY KEY (`hsc_parents_id`, `hsc_student_id`),
  INDEX `fk_hsc_parents_has_hsc_student_hsc_student1_idx` (`hsc_student_id` ASC),
  INDEX `fk_hsc_parents_has_hsc_student_hsc_parents1_idx` (`hsc_parents_id` ASC),
  CONSTRAINT `fk_hsc_parents_has_hsc_student_hsc_parents1`
    FOREIGN KEY (`hsc_parents_id`)
    REFERENCES `HSC`.`hsc_parents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_parents_has_hsc_student_hsc_student1`
    FOREIGN KEY (`hsc_student_id`)
    REFERENCES `HSC`.`hsc_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_teacher_has_hsc_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_teacher_has_hsc_class` (
  `hsc_teacher_id` INT NOT NULL,
  `hsc_class_id` INT NOT NULL,
  PRIMARY KEY (`hsc_teacher_id`, `hsc_class_id`),
  INDEX `fk_hsc_teacher_has_hsc_class_hsc_class1_idx` (`hsc_class_id` ASC),
  INDEX `fk_hsc_teacher_has_hsc_class_hsc_teacher1_idx` (`hsc_teacher_id` ASC),
  CONSTRAINT `fk_hsc_teacher_has_hsc_class_hsc_teacher1`
    FOREIGN KEY (`hsc_teacher_id`)
    REFERENCES `HSC`.`hsc_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_teacher_has_hsc_class_hsc_class1`
    FOREIGN KEY (`hsc_class_id`)
    REFERENCES `HSC`.`hsc_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_class_has_hsc_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_class_has_hsc_lesson` (
  `hsc_class_id` INT NOT NULL,
  `hsc_lesson_id` INT NOT NULL,
  PRIMARY KEY (`hsc_class_id`, `hsc_lesson_id`),
  INDEX `fk_hsc_class_has_hsc_lesson_hsc_lesson1_idx` (`hsc_lesson_id` ASC),
  INDEX `fk_hsc_class_has_hsc_lesson_hsc_class1_idx` (`hsc_class_id` ASC),
  CONSTRAINT `fk_hsc_class_has_hsc_lesson_hsc_class1`
    FOREIGN KEY (`hsc_class_id`)
    REFERENCES `HSC`.`hsc_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_class_has_hsc_lesson_hsc_lesson1`
    FOREIGN KEY (`hsc_lesson_id`)
    REFERENCES `HSC`.`hsc_lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_pratice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_pratice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_student_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `sort` TINYINT(1) NULL COMMENT '1-9',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '0撤销 1未撤销',
  `c_time` VARCHAR(45) NULL,
  `u_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `hsc_student_id`),
  INDEX `fk_hsc_pratice_hsc_student1_idx` (`hsc_student_id` ASC),
  CONSTRAINT `fk_hsc_pratice_hsc_student1`
    FOREIGN KEY (`hsc_student_id`)
    REFERENCES `HSC`.`hsc_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_commit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_commit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hsc_article_id` INT NOT NULL,
  `hsc_parents_id` INT NOT NULL,
  `content` TEXT(500) NULL,
  `stutus` TINYINT(1) NULL DEFAULT 1,
  `c_time` INT NULL,
  `u_time` INT NULL,
  PRIMARY KEY (`id`, `hsc_article_id`, `hsc_parents_id`),
  INDEX `fk_hsc_commit_hsc_article1_idx` (`hsc_article_id` ASC),
  INDEX `fk_hsc_commit_hsc_parents1_idx` (`hsc_parents_id` ASC),
  CONSTRAINT `fk_hsc_commit_hsc_article1`
    FOREIGN KEY (`hsc_article_id`)
    REFERENCES `HSC`.`hsc_article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hsc_commit_hsc_parents1`
    FOREIGN KEY (`hsc_parents_id`)
    REFERENCES `HSC`.`hsc_parents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pid` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL COMMENT '模块名称',
  `url` VARCHAR(45) NULL COMMENT '地址用U函数生成',
  `icon` VARCHAR(15) NULL COMMENT '图标',
  `sort` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '排序等级',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态',
  `c_time` INT NOT NULL,
  `u_time` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `url` VARCHAR(60) NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `sort` TINYINT(1) NULL DEFAULT 1,
  `c_time` INT NULL,
  `u_time` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `c_time_UNIQUE` (`c_time` ASC),
  UNIQUE INDEX `u_time_UNIQUE` (`u_time` ASC),
  UNIQUE INDEX `sort_UNIQUE` (`sort` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_pic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_pic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `c_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HSC`.`hsc_icon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HSC`.`hsc_icon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `c_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
